---
- block:
  - name: db checklist status file upload for prechecks Install
    import_role:
      name: dbaas_api_services
      tasks_from: db_checklist_status_file.yml
    vars:
      task_key: "{{ ansible_hostname }}"
      task_area: "ORACLE PRECHECKS"
      task_id: "{{ ticket_ref }}"
      task_status: "Upload precheck json"
      task_message: "Precheck json {{ ansible_hostname }} "
      file_mimetype: "text/plain"
      record_type: "file_upload"
      logfile_path: "{{ logfile_path }}"
      standard_task_id: "{{ standard_task_id_val }}"
    tags:
    - apex_api
  rescue:
  - name: 
    delegate_to: localhost
    lineinfile:
      path: /apex/unsent_json_body/{{ ansible_hostname }}/upload_log.json
      line: '{"checklist_id": {{ checklist_id | to_json }} }, {"logfile_path": {{ logfile_path | to_json }} }'
      create: yes
