---
#S3 public url
bin_server: https://oracle-apex-packages-repo.s3-us-west-1.amazonaws.com/MSSQL-Database
ansible_tmp: C:\Ansible\Temp
installer_location: '{{ ansible_tmp }}\mssql_bin'
#Enter an Environment (LAB, DEV, UAT, TST, QA, SIT, DR, PRD)
Env1: DEV
#What Data Center is this being built in? (GVL, NCE, NCW)
DC: NCE
#What Domain is this being installed on? (CHTR, Corp, DEV, TWCCORP, TWZDMZ, UAT)
Domain: CHTR
#Backup Path
BuPath: 'H:\Backups'
#Data Path
DataPath: 'G:\Data'
#Log Path
LogPath: 'E:\Logs'
#System Path
SystemPath: 'F:\System'
#Temdb Path
TempdbPath: 'I:'
#Enter SQL Version (2012, 2014, 2016, 2017)
SqlVersion: 2014
