---
# tasks file for mssql_AD
- include_vars: secret.yml
  no_log: True

- name: block for primary domain controller
  block:
  - name: "Change the hostname to {{ inventory_hostname }}"
    win_hostname:
      name: "{{ inventory_hostname }}"
    register: res

  - name: Reboot
    win_reboot:
    when: res.reboot_required

  - name: install ad
    win_feature:
      name:
        - AD-Domain-Services
        - DNS
      include_management_tools: yes
      include_sub_features: yes
      state: present
    register: result

  - name: let processes settle
    pause:
      minutes: 5
    delegate_to: localhost
    run_once: true

  - name: install domain
    win_domain:
      dns_domain_name: "{{ dns_name }}"
      safe_mode_password: "{{ safe_mode_password }}"
    register: ad

  - name: reboot server
    win_reboot:
      msg: "Installing AD. Rebooting..."
      pre_reboot_delay: 15
    when: ad.changed
  when: win_role == 'ad'

- name: set dns ip as fact
  set_fact:
    dns_ip: "{%- for host in play_hosts|sort -%}
            {%- if hostvars[host]['win_role'] == 'ad' -%}{{ hostvars[host]['ansible_host'] }}
            {%- endif -%}
            {%- endfor -%}"
            
