- name: AlwaysOn-Pre-Installation-Setup
#  hosts: AlwaysOn-Setup
  hosts: '{{ host }}'
  tasks:
    - name: AlwaysOn-Pre-Installation
      import_role:
        name: AlwaysOn-Pre-Installation
        tasks_from: Failover-Clustering.yml