---
# Copyright (c) 2018, 2019 Oracle and/or its affiliates.
# This software is made available to you under the terms of the GPL 3.0 license or the Apache 2.0 license.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# Apache License v2.0
# See LICENSE.TXT for details.
- name: Delete bucket
  oci_bucket:
    namespace_name: "{{ sample_object_namespace_name }}"
    compartment_id: "{{ sample_compartment_ocid }}"
    name: "{{ item }}"
    force: yes
    state: absent
  ignore_errors: yes
  with_items:
    - "{{ sample_bucket_name }}"
    - another_bucket

- name: Delete alice user
  oci_user:
    id: "{{ alice_user_ocid }}"
    state: absent
    force: yes

- name: Delete bob user
  oci_user:
    id: "{{ bob_user_ocid }}"
    state: absent
    force: yes

- name: Delete groups
  oci_group:
    id: "{{ object_readers_group_ocid }}"
    state: absent
    force: yes

- name: Delete groups
  oci_group:
    id: "{{ object_writers_group_ocid }}"
    state: absent
    force: yes

- name: Delete policies
  oci_policy:
    id: "{{ object_readers_policy_ocid }}"
    state: absent

- name: Delete policies
  oci_policy:
    id: "{{ object_writers_policy_ocid }}"
    state: absent
