---
# tasks file for aws_vms
- import_tasks: molecule.yml
  tags: [ 'never', 'molecule' ]

- name: include variables
  include_vars: secrets.yml
  no_log: True

- include_tasks: oracle.yml
  when: platform_vendor == "ORACLE"

- include_tasks: mongodb.yml
  when: platform_vendor == "MONGODB"

- include_tasks: common.yml
  when:
    - platform_vendor != "ORACLE"
    - platform_vendor != "MONGODB"
