- import_tasks: cluster_checklist_insertion.yml
  when: inventory_hostname == master_node and cluster_chklst_json_body.new_entry

- name: update the json data using PUT call
  win_uri:
    url:  "{{ apex_url }}/mssql_check_list/{{ checklist_id }}"
    validate_certs: no  # should be removed after https certs becomes renewed
    method: PUT
    body_format: json
    body: "{{ cluster_chklst_json_body }}"
    headers:
        Content-Type: "application/json"
  when:
  - inventory_hostname == master_node
  - checklist_id is defined
  - checklist_id != ""