---


- name: Checklist Insert
  block:
    - name: POST To Insert into Checklist Details
      win_uri:
        url: "{{ apex_url }}/mssql_check_list"
        validate_certs: no  # should be removed after https certs becomes renewed
        method: POST
        body_format: json
        body:
          host_name: "{{ host_name }}"
        status_code: 
          - 201
          - 200
        return_content: yes
        headers:
          Content-Type: "application/json"
      register: checklist_insrt_response

    - name: set checklist_id
      set_fact:
        checklist_id: "{{ checklist_insrt_response.json | json_query('ID') }}"

  rescue:
    - name: Store the Json If APEX Server Is Down
      delegate_to: localhost
      win_lineinfile:
        path: "{{ json_backup_dir }}/host_chklst_updates.json"
        line: '{"host_name": "{{ host_name }}", "update": {{ host_chklst_json_body | to_json }} }'
        create: yes
      when: checklist_insrt_response.status_code | int == 500 or checklist_insrt_response.status_code == -1